# Generated by Selenium IDE
from selenium import webdriver
import selenium.webdriver.common.by


class TestAddname():
    def setup_method(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def test_addname(self):
        self.open_home_page()
        self.login(username="admin", password="secret")
        self.open_name_form()
        self.fill_name_form(firstname="Raushan", lastname="Kussainova")
        self.logout()

    def open_home_page(self):
        self.driver.get("http://localhost/addressbook/")

    def login(self, username, password):
        self.driver.find_element(selenium.webdriver.common.by.By.NAME, "user").send_keys(username)
        self.driver.find_element(selenium.webdriver.common.by.By.NAME, "pass").click()
        self.driver.find_element(selenium.webdriver.common.by.By.NAME, "pass").send_keys(password)
        self.driver.find_element(selenium.webdriver.common.by.By.CSS_SELECTOR, "input:nth-child(7)").click()

    def open_name_form(self):
        self.driver.find_element(selenium.webdriver.common.by.By.LINK_TEXT, "add new").click()

    def fill_name_form(self, firstname, lastname):
        self.driver.find_element(selenium.webdriver.common.by.By.NAME, "firstname").click()
        self.driver.find_element(selenium.webdriver.common.by.By.NAME, "firstname").send_keys(firstname)
        self.driver.find_element(selenium.webdriver.common.by.By.NAME, "lastname").click()
        self.driver.find_element(selenium.webdriver.common.by.By.NAME, "lastname").send_keys(lastname)
        self.driver.find_element(selenium.webdriver.common.by.By.CSS_SELECTOR, "input:nth-child(87)").click()

    def logout(self):
        self.driver.find_element(selenium.webdriver.common.by.By.LINK_TEXT, "Logout").click()

    def teardown_method(self):
        self.driver.quit()
